version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  postgres:
    driver: local

services:
  server:
    image: gitea/gitea:${GITEA_VERSION}
    container_name: gitea-app
    environment:
      - APP_NAME=${APP_NAME}
      - RUN_MODE=${RUN_MODE}
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=db:${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_WEB_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    depends_on:
      - db

  db:
    image: postgres:${DB_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - gitea
    volumes:
      # - ./volumes/postgres:/var/lib/postgresql/data
      - postgres:/var/lib/postgresql/data